[package]
name = "alpha-geo"
version = "0.1.6"
edition = "2021"

[dependencies]
rayon = "1.7.0"
chrono = "0.4.26"
regex ="1.9.1"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
strip = true
lto = true

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]