[package]
name = "alpha-geo"
version = "0.1.1"
edition = "2021"

[dependencies]
rayon = "1.7.0"
chrono = "0.4.26"
regex ="1.9.1"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
strip = false
lto = true
