name: build

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1.0.6
      with:
        profile: minimal
        toolchain: stable
        override: true
    - name: Build
      run: cargo build --verbose
    - name: Build release
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --all-targets
    - name: Build release
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --target=x86_64-unknown-linux-gnu
    - name: Run tests
      run: cargo test --verbose