name: cross-build

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 6 */6 * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
