name: dev

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CARGO_TERM_COLOR: always

permissions:
  contents: write

on:
  workflow_call:
    inputs:
      version:
        default: '0'
        required: true
        type: string

jobs:
  pre-release:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Release
        shell: bash
        run: |
          git tag ${{ inputs.version }} && git push --tags
          gh release create ${{ inputs.version }} -t ${{ inputs.version }}

  dev-release:
    strategy:
      matrix:
        include:
          -
            target: 'x86_64-unknown-linux-musl'
            platform: 'ubuntu-latest'
          -
            target: 'x86_64-unknown-linux-gnu'
            platform: 'ubuntu-latest'
          - target: aarch64-unknown-linux-musl
            platform: ubuntu-latest
          - target: aarch64-unknown-linux-gnu
            platform: ubuntu-latest
          - target: aarch64-apple-darwin
            platform: macos-latest
          -
            target: 'x86_64-apple-darwin'
            platform: 'macos-latest'
          -
            target: 'x86_64-pc-windows-gnu'
            platform: 'windows-latest'
          -
            target: 'x86_64-pc-windows-msvc'
            platform: 'windows-latest'
    name: release - ${{ matrix.target }}
    runs-on: ${{ matrix.platform }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Upload release
        uses: taiki-e/upload-rust-binary-action@v1.16.0
        with:
          bin: alpha-geo-dev
          target: ${{ inputs.target }}
          archive: $bin-$target
          ref: refs/tags/${{ inputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}