name: in

permissions:
  contents: write

on:
  workflow_call:
    inputs:
      target:
        default: x86_64-apple-darwin
        required: false
        type: string
      platform:
        default: macos-latest
        required: false
        type: string
      release:
        default: false
        required: false
        type: boolean

jobs:
  tag:
    uses: ./.github/workflows/cargo-tag.yml
  build:
    name: publish - ${{ inputs.target }}
    runs-on: ${{ inputs.platform }}
    needs:
      - tag
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3

      - 
        name: Install Rust
        uses: actions-rs/toolchain@v1.0.6
        with:
          profile: minimal
          toolchain: stable
          override: true

      - 
        if: inputs.platform == 'ubuntu-latest'
        run: sudo chown -R $(whoami):$(id -ng) ~/.cargo/

      - 
        name: Cache Cargo Registry
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ inputs.platform }}-cargo-registry-${{ hashFiles('**/Cargo.toml') }}

      - 
        name: Build only
        if: ${{ inputs.release == false }}
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target=${{ inputs.target }}
      
      - 
        name: Upload release
        if: ${{ inputs.release == true }} 
        uses: taiki-e/upload-rust-binary-action@v1.16.0
        with:
          bin: alpha-geo
          target: ${{ inputs.target }}
          archive: $bin-$target
          ref: refs/tags/v${{ needs.tag.outputs.ver }}
          token: ${{ secrets.GITHUB_TOKEN }}

