name: publish

env:
  CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CARGO_TERM_COLOR: always

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.*
  workflow_run:
    workflows: ['auto-tag']
    types:
      - completed
jobs:
  build:
    name: publish - ${{ matrix.target }}
    strategy:
      matrix:
        include:
          -
            target: 'x86_64-unknown-linux-musl'
            platform: 'ubuntu-latest'
          -
            target: 'x86_64-pc-windows-gnu'
            platform: 'windows-latest'
          -
            target: 'x86_64-apple-darwin'
            platform: 'macos-latest'

    runs-on: ${{ matrix.platform }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3

      - 
        name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - 
        if: matrix.platform == 'ubuntu-latest'
        run: sudo chown -R $(whoami):$(id -ng) ~/.cargo/

      - 
        name: Cache Cargo Registry
        uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: ${{ matrix.platform }}-cargo-registry-${{ hashFiles('**/Cargo.toml') }}

      - 
        name: Build release
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-targets

