name: auto-tag

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      tag:
        description: manual trigger
        required: true
        default: '0'

jobs:
  create-tag:
    runs-on: "ubuntu-latest"
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3

      - 
        name: Get
        id: tag
        shell: bash
        run: |
          echo VERSION=$(awk -F ' = ' '$1 ~ /version/ { gsub(/["]/, "", $2); printf("%s",$2) }' Cargo.toml) >> $GITHUB_OUTPUT

      - 
        name: Set
        shell: bash
        run: |
          git tag v${{ steps.tag.outputs.VERSION }} && git push --tags